#+TITLE: Now
#+options: H:6

* Now Page
:LOGBOOK:
CLOCK: [2023-10-25 Wed 12:40]--[2023-10-25 Wed 12:45] =>  0:05
CLOCK: [2023-10-25 Wed 10:53]--[2023-10-25 Wed 10:56] =>  0:03
:END:
#+begin_verse
/Last updated: 2023-10-25/
#+end_verse
What I'm up to right now.

** 🥕 Health
I'm in my early 30s and I think my top focus for the rest of my life should be health and longevity. Most of the influence in this space comes from two sources:
*** How not to die
The website [[https://nutritionfacts.org/][nutritionfacts.org]] is the biggest influence. A doctor reviews nutrition and medical journals and distills the findings into content for regular people. tl;dr ... eat whole food plant based and your chance of dying from virtually every major risk factor decreases. I bought [[https://nutritionfacts.org/book/how-not-to-die-cookbook/][the cookbook]] and have been trying to make that a majority of my diet. I'm still regularly consuming dairy and eggs but consumption is trending down.
*** Blueprint

*** My protocol

** 🛠️ Production
*** Lo Mirli
*** Garden

** 👀 Intentional Consumption
*** Farming
I'm still harboring a fantasy of quitting tech and becoming a farmer.
- [[https://www.youtube.com/c/REDGardens][Red Gardens]]
High signal quantitative and qualitative analysis of multiple gardening techniques in Ireland.
- [[https://www.youtube.com/channel/UCznk4o83WjKFCwEZ8th8wHQ][Edible Acres]]
Consumption thoughtful nursery and composting system in New York state.
- [[https://www.youtube.com/channel/UCLhu5JoRWPgEGDoUFfQHTPQ/videos][No till growers]]
High production value no-till related.
- [[https://www.notillgrowers.com/the-composter][The Composter]]
A podcast interviewing different /high quality compost/ operations.
*** SASS Business
Since I started writing software professionally I've consumed entrepreneur content. This is the stuff I like the most.
- [[https://www.startuptolast.com/][Startup to Last]]
My favorite "two people talking" show about /bootstrappy/ tech companies. I listen to a few of them -- too many to list here. So I'll just mention this one. I think these two most align with my values and are just constantly talking about things I find interesting.
- [[https://www.indiehackers.com/podcasts][Indie Hackers]]
Courtland is a really good podcast host. Early episodes are interview style. I've listened to each episode two or three times. Later episodes are more conversational. This is just a good resource to get immersed and have the basics reiterated over and over.
*** Environment
I'm becoming more interested in urbanism and climate change and I like these sources of information.
- [[https://www.youtube.com/@CityNerd][City Nerd]]
The common themes are walkability, density, and public transportation. Lots of deadpan humor and sarcasm. Also deep quantitative dives and qualitative first hand accounts of experiences across cities in the United States.
- [[https://www.youtube.com/playlist?list=PLnNZYWyBGJ1GLPmb55WQAln2Q7rZn5AFX][PBS Terra - Weathered]]
Non alarmist, but still alarming, generally accessible explanations of climate change topics. I watch these to feel better about living in the midwest.
