#+TITLE: Now
#+options: H:6

* Now Page
:LOGBOOK:
CLOCK: [2023-10-25 Wed 12:40]--[2023-10-25 Wed 12:45] =>  0:05
CLOCK: [2023-10-25 Wed 10:53]--[2023-10-25 Wed 10:56] =>  0:03
:END:
#+begin_verse
/Last updated: 2023-10-25/
#+end_verse
What I'm up to right now.

** 🥕 Health
I'm in my early 30s and I think my top focus for the rest of my life should be health and longevity. Most of the influence in this space comes from two sources:
*** How not to die
The website [[https://nutritionfacts.org/][nutritionfacts.org]] is the biggest influence. A doctor reviews nutrition and medical journals and distills the findings into content for regular people. tl;dr ... eat whole food plant based and your chance of dying from virtually every major risk factor decreases. I bought [[https://nutritionfacts.org/book/how-not-to-die-cookbook/][the cookbook]] and have been trying to make that a majority of my diet. I'm still regularly consuming dairy and eggs but consumption is trending down.
*** Blueprint

*** My protocol

** 🛠️ Production
*** Lo Mirli
*** Garden

** 👀 Intentional Consumption
*** Farming
I'm still harboring a fantasy of quitting tech and becoming a farmer.
- [[https://www.youtube.com/c/REDGardens][Red Gardens]]
High signal quantitative and qualitative analysis of multiple gardening techniques in Ireland.
- [[https://www.youtube.com/channel/UCznk4o83WjKFCwEZ8th8wHQ][Edible Acres]]
Consumption thoughtful nursery and composting system in New York state.
- [[https://www.youtube.com/channel/UCLhu5JoRWPgEGDoUFfQHTPQ/videos][No till growers]]
High production value no-till related.
- [[https://www.notillgrowers.com/the-composter][The Composter]]
A podcast interviewing different /high quality compost/ operations.
*** SASS Business
Since I started writing software professionally I've consumed entrepreneur content. This is the stuff I like the most.
- Startup to Last
- Indie Hackers
*** Environment
I'm becoming more interested in urbanism and climate change and I like these sources of information.
- [[https://www.youtube.com/@CityNerd][City Nerd]]
The common themes are walkability, density, and public transportation. Lots of deadpan humor and sarcasm. Also deep quantitative dives and qualitative first hand accounts of experiences across cities in the United States.
- PBS Terra
Non alarmist, but still alarming, generally accessible explanations of climate change.
